//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.EquipmentRecords = new HashSet<EquipmentRecords>();
        }
    
        public int employee_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public int departament_id { get; set; }
        public string home_address { get; set; }
        public string phone_number { get; set; }
        public string email_address { get; set; }
    
        public virtual Departaments Departaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentRecords> EquipmentRecords { get; set; }
    }
}
