//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRecords
    {
        public int equipment_record_id { get; set; }
        public int equipment_id { get; set; }
        public string accounting_code { get; set; }
        public System.DateTime purchase_date { get; set; }
        public decimal cost { get; set; }
        public Nullable<int> owner_employee_id { get; set; }
        public Nullable<int> owner_departament_id { get; set; }
        public int state_id { get; set; }
        public Nullable<int> purchase_year { get; set; }
    
        public virtual Departaments Departaments { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentStates EquipmentStates { get; set; }
    }
}
